### ISSUE TITLE
Question: Why is BusinessId needed in multiple places?

### ISSUE THREAD

**Issue by toqueteos** [payvision-development/payvision-sdk-php#3]
What's the point of requiring `business ID` as third parameter of `ApiConnection`?

The `RequestObjectBuilder` as shown in the README does require it again.

**Comment by kanduvisla** [comment]
Hi @toqueteos ,

In the 2.0 version of the SDK the Business ID will be removed from the `ApiConnection` constructor. The Business ID is part of your request, not of your credentials.

**Comment by ghost** [comment]
@toqueteos: closing this issue as v2.0.0 is released and Business ID has been removed from ```ApiConnection``` constructor.
