### ISSUE TITLE
Getting HTTP/1.1 401 Unauthorized upon calling $apiResponse = $apiConnection->execute($apiRequest);

### ISSUE THREAD

**Issue by khairulhasanmd** [payvision-development/payvision-sdk-php#4]
**Describe the bug**
I am getting the following output instead json upon calling $apiResponse = $apiConnection->execute($apiRequest);. 

* Trying 193.105.144.151:443... * TCP_NODELAY set * Trying 2001:67c:276c:32::151:443... * TCP_NODELAY set * Immediate connect fail for 2001:67c:276c:32::151: Network is unreachable * Connected to stagconnect.acehubpaymentservices.com (193.105.144.151) port 443 (#0) * ALPN, offering http/1.1 * successfully set certificate verify locations: * CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs * SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384 * ALPN, server did not agree to a protocol * Server certificate: * subject: C=NL; L=Amsterdam; O=Payvision BV; CN=*.acehubpaymentservices.com * start date: May 11 00:00:00 2020 GMT * expire date: May 19 12:00:00 2021 GMT * subjectAltName: host "stagconnect.acehubpaymentservices.com" matched cert's "*.acehubpaymentservices.com" * issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA * SSL certificate verify ok. > POST /gateway/v3/payments HTTP/1.1 Host: stagconnect.acehubpaymentservices.com User-Agent: GuzzleHttp/6.5.0 curl/7.68.0 PHP/7.4.3 Content-Type: application/json Authorization: Basic anptYXJrZXRpbmc6QXlVWjk1RXA4M2l5S3M4ZQ== Content-Length: 301 * upload completely sent off: 301 out of 301 bytes * Mark bundle as not supporting multiuse < HTTP/1.1 401 Unauthorized < Transfer-Encoding: chunked < Strict-Transport-Security: max-age=2592000 < Date: Thu, 03 Sep 2020 16:55:54 GMT < * Connection #0 to host stagconnect.acehubpaymentservices.com left intact Request: { "header": { "businessId": "{123456}" }, "body": { "transaction": { "amount": 10, "trackingCode": "7F4BFD5D-55E4-4775-81F7-0784188876C7", "currencyCode": "EUR", "storeId": 1, "brandId": 1010 }, "card": { "cvv": "123", "expiryMonth": 3, "expiryYear": 2024, "holderName": "John Doe", "number": "4711100000000000" } }, "action": "payment" } Response: { "_raw_response": "" }

**To Reproduce**
I have used the following code as shown in the example. The credentials are removed.

    private $apiConnection;

    public function __construct()
    {
        $apiConnection = new ApiConnection(
				    'username',
				    'password',
				    ApiConnection::URI_TEST,    // =URL to connect to, optional
				    false                       // debug mode, see debugging
				);
    }

    /**
     * function: charge
     * 
     */
    public function charge()
    {
        $explode = explode("/", '03/24');

        try {
            $paymentRequestBuilder = new PaymentRequestBuilder();
            $paymentRequestBuilder->header()->setBusinessId('{123456}');
            $paymentRequestBuilder->body()->card()
                ->setHolderName('John Doe')
                ->setNumber('4711100000000000')
                ->setExpiryMonth($explode[0])
                ->setExpiryYear("20" . $explode[1])
                ->setCvv('123');
            $paymentRequestBuilder->body()->transaction()
                ->setAmount(10.00)
                ->setBrandId('1010')
                ->setStoreId(1)
                ->setTrackingCode('7F4BFD5D-55E4-4775-81F7-0784188876C7')
                ->setCurrencyCode('EUR');
            // $paymentRequestBuilder->setAction(PaymentRequest::ACTION_AUTHORIZE);
            $paymentRequestBuilder->setAction(PaymentRequest::ACTION_PAYMENT);
            $requestObject = $paymentRequestBuilder->build();

            $apiRequest = RequestBuilder::newPayment($requestObject);
            $apiResponse = $this->apiConnection->execute($apiRequest);
            return [
                "success" => true,
                "message" => $apiResponse,
            ];

        } catch (ErrorResponse $errorResponseException) {
            $errorResponse = $errorResponseException->getErrorResponse();
            return [
                "success" => false,
                "message" => $errorResponse,
            ];
        }
    
    }

**Desktop (please complete the following information):**
 - OS: Lubuntu

**Comment by kanduvisla** [comment]
Hi @khairulhasanmd ,

I see in your example that you've put brackets around your business ID:

    $paymentRequestBuilder->header()->setBusinessId('{123456}');

Is this because you also obfuscated this in the example?

**Comment by khairulhasanmd** [comment]
I was blindly following the example from https://github.com/payvision-development/payvision-sdk-php#creating-a-payment-request
Thanks for pointing it out. Removing curly braces from there works actually. But this shows up a new error "Invalid or missing parameter".
 

*Trying193.105.144.151: 443...*TCP_NODELAYset*Trying2001: 67c: 276c: 32: : 151: 443...*TCP_NODELAYset*Immediateconnectfailfor2001: 67c: 276c: 32: : 151: Networkisunreachable*Connectedtostagconnect.acehubpaymentservices.com(193.105.144.151)port443(#0)*ALPN,
offeringhttp/1.1*successfullysetcertificateverifylocations: *CAfile: /etc/ssl/certs/ca-certificates.crtCApath: /etc/ssl/certs*SSLconnectionusingTLSv1.2/ECDHE-RSA-AES256-GCM-SHA384*ALPN,
serverdidnotagreetoaprotocol*Servercertificate: *subject: C=NL;L=Amsterdam;O=PayvisionBV;CN=*.acehubpaymentservices.com*startdate: May1100: 00: 002020GMT*expiredate: May1912: 00: 002021GMT*subjectAltName: host"stagconnect.acehubpaymentservices.com"matchedcert's"*.acehubpaymentservices.com"*issuer: C=US;O=DigiCertInc;CN=DigiCertSHA2SecureServerCA*SSLcertificateverifyok.>POST/gateway/v3/paymentsHTTP/1.1Host: stagconnect.acehubpaymentservices.comUser-Agent: GuzzleHttp/6.5.0curl/7.68.0PHP/7.4.3Content-Type: application/jsonAuthorization: BasicanptYXJrZXRpbmc6QXlVWjk1RXA4M2l5S3M4ZQ==Content-Length: 291*uploadcompletelysentoff: 291outof291bytes*Markbundleasnotsupportingmultiuse<HTTP/1.1400BadRequest<Content-Length: 393<Content-Type: application/json;charset=utf-8<Strict-Transport-Security: max-age=2592000<Date: Wed,
09Sep202011: 37: 17GMT<*Connection#0tohoststagconnect.acehubpaymentservices.comleftintact
Request: {
  "header": {
    "businessId": "123456"
  },
  "body": {
    "transaction": {
      "amount": 1,
      "trackingCode": "7F4BFD5D-55E4-4775-1599651435",
      "currencyCode": "EUR",
      "storeId": 1,
      "brandId": 1010
    },
    "card": {
      "cvv": "123",
      "expiryMonth": 3,
      "expiryYear": 2024,
      "holderName": "John Doe",
      "number": "4111111111111111"
    }
  },
  "action": "payment"
}
Response: {
  "result": -1,
  "description": "Input error",
  "header": {
    "requestTimestamp": "2020-09-09T11:37:16Z"
  },
  "body": {
    "error": {
      "code": 300103300,
      "message": "Invalid or missing parameter",
      "detailedMessage": "Invalid or missing parameter"
    },
    "transaction": {
      "amount": 1,
      "currencyCode": "EUR",
      "action": "payment",
      "id": "55a80ed8-3f7d-43d2-b0de-03e15082c041",
      "trackingCode": "7F4BFD5D-55E4-4775-1599651435",
      "brandId": 1010
    }
  }
}

Am I missing any parameter?

**Comment by kanduvisla** [comment]
@khairulhasanmd Have you tried prefixing the expirymonth with a leading zero? Of format the amount with a decimal separator?

If I look at the [documentation](https://developers.acehubpaymentservices.com/v3.3/reference#payment-3-1) I see the format for the `expiryMonth` is `MM`, and `amount` should be formatted [according to ISO 4217](https://developers.acehubpaymentservices.com/docs/data-types) which means `1.00` instead of `1`.

That might trigger the input errors. Could you please change that in your code and see if it works?

**Comment by khairulhasanmd** [comment]
Thanks for your comment. I am still getting the error. I will find a way to fix it.
