### ISSUE TITLE
getPayments function on the Payments\Service\RequestBuilder class not working properly

### ISSUE THREAD

**Issue by casberkman1** [payvision-development/payvision-sdk-php#5]
The getPayments function on the Payments\Service\RequestBuilder class does not work. It looks like its because the $jsonResponse variable in the ApiConnection class on line 247 contains an array of payments instead of one.

```php
        $apiRequest = RequestBuilder::getPayments($businessId, $orderId);

        $apiResponse = $this->apiConnection->execute($apiRequest, $this->requestHeaders);
```

In the ApiConnection class on line 247 you see the following line:

```php
            $response = JsonToObject::build($targetClass, $jsonResponse);
```
$jsonResponse is an empty array.

If I change it to this it returns a body with a transaction as expected.
```php
            $response = JsonToObject::build($targetClass, $jsonResponse[0]);
```

Here you see the exception: https://flareapp.io/share/KPgk2YeP

Thanks in advance!

**Comment by ghost** [comment]
Hi @casberkman1, 
Thanks for raising the issue. We are reviewing it and fix it in the next release.

**Comment by kanduvisla** [comment]
Hi @casberkman1 ,

This issue is a case of bad documentation; if you as a developer know the API will return an array (which is the case with the specific GET payments endpoint), you need to use the `ApiConnection::executeAndReturnArray()`-method instead of the `execute()`-method.

If you change your call to this it will work:

```php
$apiRequest = RequestBuilder::getPayments($businessId, $trackingCode);
$apiResponses = $this->apiConnection->executeAndReturnArray($apiRequest, $this->requestHeaders);
$apiResponse = $apiResponses[0]; // for example
```

We've created an internal ticket to improve the documentation on this subject.

**Comment by casberkman1** [comment]
Hi @kanduvisla ,

Thanks for your quick response. I will try that!

**Comment by kanduvisla** [comment]
Hi @casberkman1 ,

The SDK is updated to the latest version with the updated documentation.

**Comment by mvela-payvision** [comment]
Unfortunately, v7.0.0 of the sdk had to be removed. The release is postponed to January 2021.
