### ISSUE TITLE
Paymentlink created by the SDK throws a console error 400 when trying to pay via the checkout.

### ISSUE THREAD

**Issue by casberkman1** [payvision-development/payvision-sdk-php#6]
When I create a payment link via the `PaymentlinkRequestBuilder::newLink($requestObject); ` function I get a created payment link but when I try to pay via the link I get an error, as shown below. The console gives me the following error when I click the pay button:

<img width="813" alt="Schermafbeelding 2021-01-11 om 13 01 39" src="https://user-images.githubusercontent.com/25476495/104180236-2fe86700-540d-11eb-9e60-6a282ee618c4.png">

<img width="651" alt="Schermafbeelding 2021-01-11 om 12 40 08" src="https://user-images.githubusercontent.com/25476495/104180672-cd439b00-540d-11eb-8348-ae64bf320b5c.png">

So I tried some things and read the API documentation. I saw that the 'purchase id' parameter is not a required one but in the example in the sandbox right here: https://sandbox.acehubpaymentservices.com/ at the create payment link section it shows a request body with a transaction with a purchase id. I tried the generated url from the response in the browser with the request from the sandbox and it worked just fine, no errors whatsoever.

I checked the differences between this sandbox request object and my own and saw that I didnt provided a purchase id for the transaction but as far as i can see there is no option to set the purchase id in the `Payvision\SDK\Domain\Paymentlinks\Service\Builder\Link\RequestTransaction` class.

I also tried to remove the purchase id parameter from the transaction in the sandbox and when I did that I encountered the same issue as I had locally.

So Im not sure why the API docs say it isnt a required parameter because the paymentlink doesnt work if you do not provide the transaction with a purchase id. Maybe the documentation isnt correct on this part? maybe I do something wrong myself. 

I think my problem will be fixed when there will be an option to set the purchase id in the `Payvision\SDK\Domain\Paymentlinks\Service\Builder\Link\RequestTransaction` class.

Thanks in advance!

**Comment by ghost** [comment]
Hi @casberkman1, thanks for sharing this issue. Our development team is actively working on a solution.

According to the documentation `puchaseId` field is a conditional field. It means it is only required for specific brands, like iDEAL. If your checkout includes iDEAL in the brands list, the puchase id must be included.

**Comment by casberkman1** [comment]
Hi @mvela-payvision thank you for your response and explanation. 

Do you have any idea or indication when your development team will be able to publish a possible fix for this?

Thanks!

**Comment by ghost** [comment]
Hi @casberkman1 ,

This issue is fixed in [v.8.0.0](https://github.com/payvision-development/payvision-sdk-php/releases/tag/8.0.0)
